easy_admin:
    site_name: 'DevCollab Admin'
    user:
        display_name: true
        display_avatar: true
    entities:
        Users:
            class: App\Entity\Users
            label: 'Users'
            list:
                filters: ['name','last_name','town']
                title: "%%entity_label%% List"
                max_results: 20
                fields:
                    - id
                    - name
                    - lastname
                    - { property: 'email', type: 'email'}
                    - town
                    - { property: 'github_username',label: "GitHub" }
            form:
                fields:
                    - { property: 'name', type: 'text', label: 'First Name', type_options: { required: true } }
                    - { property: 'lastname', type: 'text', label: 'Last Name' }
                    - { property: 'email', type: 'email', label: 'Email', type_options: { required: true } }
                    - town
                    - password
                    - short_description
                    - skills
        Skills:
            class: App\Entity\Skills
        Skill:
            class: App\Entity\Skill
        Teams:
            class: App\Entity\Teams
        Teampoints:
            class: App\Entity\Teampoints
        Teamtasks:
            class: App\Entity\Teamtasks
        Projects:
            class: App\Entity\Projects
        Projectdetails:
            class: App\Entity\Projectdetails

    design:
        brand_color: '#1ABC9C'
        menu:
            - { label: 'Users' }
            - { entity: 'Users', css_class: 'default', icon: 'user' }
            - { entity: 'Skills', css_class: 'default', icon: 'book' }
            - { label: 'Teams' }
            - { entity: 'Teamstasks', css_class: 'default', icon: 'tasks' }
            - { entity: 'Teams', css_class: 'default', icon: 'group' }
            - { label: 'Admin' }
            - { entity: 'Skill', css_class: 'default', icon: 'cogs' }
            - { entity: 'Teamspoints', css_class: 'default', icon: 'award' }
            - { label: 'Project' }
            - { entity: 'Projects', css_class: 'default', icon: 'code-branch' }
            - { entity: 'Projectdetails', css_class: 'default', icon: 'code-branch' }
